"""empty message

Revision ID: 808bc27520ca
Revises: 
Create Date: 2019-04-10 16:08:42.152488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808bc27520ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('cid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'course', ['cid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'cid')
    # ### end Alembic commands ###
