"""empty message

Revision ID: c154bc77244e
Revises: 
Create Date: 2019-04-15 11:34:39.203357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c154bc77244e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=32), nullable=False),
    sa.Column('upwd', sa.String(length=32), nullable=False),
    sa.Column('uphone', sa.String(length=32), nullable=False),
    sa.Column('uemail', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uphone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
